export const GET_LIST = 'GET_LIST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAIL = 'GET_LIST_FAIL';

export const NEXT_PLAYER = 'NEXT_PLAYER';
export const NEXT_PLAYER_CALL_SUCCESS = 'NEXT_PLAYER_CALL_SUCCESS';
export const NEXT_PLAYER_CALL_FAIL = 'NEXT_PLAYER_CALL_FAIL';
